### PR TITLE
Typos readability

### PR DESCRIPTION
**Pull request by mweidling**
In particular the spelling has been switched to American English which is more common in Computer Science related fields.

### CODE REVIEW

**Comment by yoannspace** [comment]
Thanks for the many fixes in the documents. However, the "switch" to American English might be unnecessary.

**Comment by schildwaechter** [comment]
Yes, we should stick to British, see our new Contributing Rules, 0195b67.

**Review by schildwaechter — APPROVED** [review]
Very good improvements to legibility, thanks.

**Comment by yoannspace** [comment]
Was this supposed to be merged before reverting the US/UK English?

**Comment by schildwaechter** [comment]
I did spellcheck with en_GB in dcf3dfa before merging.

**Comment by yoannspace** [comment]
Sorry, but for example: https://en.oxforddictionaries.com/definition/internationalization
See https://github.com/DARIAH-ERIC/technical-reference/pull/5/files#diff-26960ed46f357f1fb6e92c3960f94a6bL3

**Comment by schildwaechter** [comment]
You are right, my mistake.
Turns out `hunspell -d en_GB` accepts both, which is why I missed it.
As the Oxford Guide says 'ise' in contrast to hunspell's suggestion of 'ize' for technical writing, I clarified the contribution guides accordingly, see 7717548.

**Pull request merged**
